image: node:16

pipelines:
 pull-requests:
    '**':
      - step:
          name: 'Build and test affected apps on Pull Requests'
          caches:
            - node
          script:
            - npm ci
            - npx nx affected --target=test --base=origin/main --parallel